//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWinApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalDebit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalDebit()
        {
            this.ExternalDebitTransactions = new HashSet<ExternalDebitTransaction>();
        }
    
        public long ID { get; set; }
        public System.DateTime DebitDate { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PersonName { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public decimal Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalDebitTransaction> ExternalDebitTransactions { get; set; }
    }
}
