//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWinApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemUnit()
        {
            this.ItemPrices = new HashSet<ItemPrice>();
            this.ItemQuantities = new HashSet<ItemQuantity>();
        }
    
        public long ID { get; set; }
        public long ItemID { get; set; }
        public long UnitID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemQuantity> ItemQuantities { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
