//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWinApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategorySupplier
    {
        public long ID { get; set; }
        public long SupplierID { get; set; }
        public long ItemCategoryID { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
