//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWinApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOrderItem
    {
        public long ID { get; set; }
        public long ItemID { get; set; }
        public long SellOrderID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public double Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SellOrder SellOrder { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
