//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWinApplication.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDataEntities : DbContext
    {
        public ShopDataEntities()
            : base("name=ShopDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyOrder> BuyOrders { get; set; }
        public virtual DbSet<BuyOrderItem> BuyOrderItems { get; set; }
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<CreditTransaction> CreditTransactions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Debit> Debits { get; set; }
        public virtual DbSet<DebitTransaction> DebitTransactions { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<ExternalCredit> ExternalCredits { get; set; }
        public virtual DbSet<ExternalCreditTransaction> ExternalCreditTransactions { get; set; }
        public virtual DbSet<ExternalDebit> ExternalDebits { get; set; }
        public virtual DbSet<ExternalDebitTransaction> ExternalDebitTransactions { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemCategorySupplier> ItemCategorySuppliers { get; set; }
        public virtual DbSet<ItemPrice> ItemPrices { get; set; }
        public virtual DbSet<ItemQuantity> ItemQuantities { get; set; }
        public virtual DbSet<ItemUnit> ItemUnits { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<SellOrder> SellOrders { get; set; }
        public virtual DbSet<SellOrderItem> SellOrderItems { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
